#if defined(SOFTDEVICE_PRESENT)

#define PEER_MANAGER_ENABLED 1
#define BLE_ADVERTISING_ENABLED 1



#define FDS_ENABLED 1
#define FDS_CHUNK_QUEUE_SIZE 8
#define FDS_OP_QUEUE_SIZE 4
#define FDS_VIRTUAL_PAGES 3
#define FDS_MAX_USERS 8
#define FDS_VIRTUAL_PAGE_SIZE 1024

#define FSTORAGE_ENABLED 1
#define FS_QUEUE_SIZE 4
#define FS_OP_MAX_RETRIES 3
#define FS_MAX_WRITE_SIZE_WORDS 1024


#endif